// spazaQuestions.ts
import { Question } from "@/app/types";

export const SpazaCompanyQuestions: Question[] = [
  {
    id: "1",
    section: "Business details",
    name: "company_name",
    label: "Company / Trading Name",
    inputType: "text",
    required: true,
  },
  {
    id: "2",
    section: "Owner Personal Details",
    name: "owner_name",
    label: "Owner’s Full Name",
    inputType: "text",
  },
  {
    id: "3",
    section: "",
    name: "owner_contact_details_mobile",
    label: "Owner contact details (Call & Whatsapp)",
    inputType: "tel",
  },
  {
    id: "4",
    section: "",
    name: "owner_contact_details_email",
    label: "Email Address",
    inputType: "text",
  },
  {
    id: "5",
    section: "Business Type",
    name: "business_type",
    label: "What type of business?",
    inputType: "radio",
    options: [
      "Sole Proprietor",
      "Pty Ltd",
      "Cooperative",
      "Informal (Not Yet Registered)",
    ],
  },
  {
    id: "6",
    section: "Financial Profile",
    name: "monthly_revenue",
    label: "Monthly Revenue",
    inputType: "radio",
    options: [
      "R70,000 - 150,000",
      "R30,000 – R70,000",
      "R10,000 – R30,000",
      "R1000 - R10,000",
    ],
  },
  {
    id: "7",
    section: "Banking & Financial Services",
    name: "banks_used",
    label: "Which bank(s) do you use?",
    inputType: "checkbox",
    options: [
      "Standard Bank",
      "FNB",
      "Nedbank",
      "ABSA",
      "Capitec",
      "TymeBank",
      "Other",
    ],
  },
  {
    id: "8",
    section: "The areas you would like us to support you in",
    name: "support_needs",
    label: "What support do you need?",
    inputType: "checkbox",
    options: [
      "Access to competitive suppliers and bulk stock ",
      "Help with business registration/Compliance issues",
      "Access to funding / loans / grants ",
      "Training on running and growing the shop ",
      "Digital tools for managing sales & stock ",
      "Bookkeeping (Financial Reports) ",
    ],
  },
];
