import { Question } from "@/app/types";

export const SpazaSupplierQuestions: Question[] = [
  {
    id: "1",
    section: "Stock Sourcing",
    name: "stock_sources",
    label: "Where do you usually buy your stock?",
    inputType: "checkbox",
    required: false,
    options: [
      "Local wholesalers (e.g., Devland, Jumbo, Boxer)",
      "Large supermarkets (e.g., Shoprite, Pick n Pay)",
      "Direct from distributors (delivery trucks, agents)",
      "Other spaza shops",
      "Informal / street suppliers"
    ],
  },
  {
    id: "2",
    section: "Product Mix",
    name: "products_most_often",
    label: "Which products do you buy most often?",
    inputType: "checkbox",
    required: false,
    options: [
      "Bread",
      "Cooldrinks & Juices",
      "Maize Meal / Rice / Flour",
      "Sugar & Cooking Oil",
      "Airtime & Data Vouchers",
      "Tobacco & Cigarettes",
      "Household Products (soap, washing powder, candles, paraffin)",
      "Other"
    ],
  },
  {
    id: "3",
    section: "Product Mix",
    name: "other_products_specify",
    label: "Please specify other products",
    inputType: "text",
    required: false,
  },
  {
    id: "4",
    section: "Stock Management",
    name: "stock_frequency",
    label: "How often do you buy stock?",
    inputType: "radio",
    required: true,
    options: [
      "Daily",
      "2–3 times per week",
      "Once per week",
      "Once every two weeks or more"
    ],
  },
  {
    id: "5",
    section: "Stock Management",
    name: "stock_delivery_method",
    label: "Do you get your stock delivered, or do you fetch it yourself?",
    inputType: "radio",
    required: true,
    options: [
      "Delivered to the shop",
      "I fetch it myself (taxi, bakkie, etc.)"
    ],
  },
  {
    id: "6",
    section: "Supplier Challenges",
    name: "supplier_challenges",
    label: "What challenges do you face with suppliers?",
    inputType: "checkbox",
    required: false,
    options: [
      "Prices are too high",
      "No bulk discounts",
      "Transport costs are too expensive",
      "Stock delivery is unreliable",
      "Limited product choice",
      "Suppliers don't give credit",
      "Quality of products",
      "Other"
    ],
  },
  {
    id: "7",
    section: "Supplier Challenges",
    name: "other_challenges_specify",
    label: "Please specify other challenges",
    inputType: "text",
    required: false,
  },
  {
    id: "8",
    section: "Credit Terms",
    name: "suppliers_give_credit",
    label: "Do your suppliers give you stock on credit?",
    inputType: "radio",
    required: true,
    options: [
      "Yes",
      "No"
    ],
  },
  {
    id: "9",
    section: "Credit Terms",
    name: "credit_days",
    label: "For how many days do they give credit?",
    inputType: "text",
    required: false,
  },
  {
    id: "10",
    section: "Payment Methods",
    name: "payment_methods",
    label: "How do you usually pay your suppliers?",
    inputType: "checkbox",
    required: false,
    options: [
      "Cash only",
      "EFT / Bank Transfer",
      "Mobile Money (MTN MoMo, Kazang, etc.)",
      "Card payment (Speedpoint, Yoco, etc.)"
    ],
  },
  {
    id: "11",
    section: "Supplier Reliability",
    name: "supplier_trust",
    label: "Do you trust your current suppliers to deliver on time and at the right price?",
    inputType: "radio",
    required: true,
    options: [
      "Yes, always",
      "Sometimes",
      "No, I have many issues"
    ],
  },
  {
    id: "12",
    section: "Bulk Buying Interest",
    name: "bulk_buying_interest",
    label: "Would you be interested in joining a bulk-buying group with other spaza shops to get lower prices?",
    inputType: "radio",
    required: true,
    options: [
      "Yes",
      "No",
      "Maybe, if it saves me money"
    ],
  },
  {
    id: "13",
    section: "Product Needs",
    name: "products_want_cheaper",
    label: "Which products would you want cheaper or more reliable supply for?",
    inputType: "text",
    required: false,
  },
  {
    id: "14",
    section: "Current Suppliers",
    name: "supplier_1",
    label: "Supplier 1",
    inputType: "text",
    required: false,
  },
  {
    id: "15",
    section: "Current Suppliers",
    name: "supplier_2",
    label: "Supplier 2",
    inputType: "text",
    required: false,
  },
  {
    id: "16",
    section: "Current Suppliers",
    name: "supplier_3",
    label: "Supplier 3",
    inputType: "text",
    required: false,
  },
  {
    id: "17",
    section: "Current Suppliers",
    name: "supplier_4",
    label: "Supplier 4",
    inputType: "text",
    required: false,
  },
  {
    id: "18",
    section: "Current Suppliers",
    name: "supplier_5",
    label: "Supplier 5",
    inputType: "text",
    required: false,
  },
  {
    id: "19",
    section: "Current Suppliers",
    name: "other_suppliers",
    label: "Other suppliers",
    inputType: "text",
    required: false,
  },
  {
    id: "20",
    section: "Supplier Selection",
    name: "supplier_selection_reasons",
    label: "What are the main reasons you choose to buy from these suppliers?",
    inputType: "checkbox",
    required: false,
    options: [
      "Price / affordability",
      "Proximity / convenience (close to shop)",
      "Credit facilities (buy now, pay later)",
      "Reliability / consistent stock availability",
      "Quality of products",
      "Variety of products",
      "Other"
    ],
  },
  {
    id: "21",
    section: "Supplier Selection",
    name: "other_selection_reasons_specify",
    label: "Please specify other reasons",
    inputType: "text",
    required: false,
  },
];