import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SpazaHub Questionnaire",
  description: "Generated by SpazaHub",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <Link href="/" className="fixed top-3 left-3 bg-green-500 text-black hover:bg-green-600 rounded">
          <div className=" text-center border text-gray-600 px-1 py-1 shadow-lg">
                Home
          </div>
            </Link>
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
